spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Jerry.entity
  configuration:
    map-underscore-to-camel-case: true
